MAX_SELECTED_DOMAINS = 3
MAX_SECONDARY_DOMAINS = 2
MAX_LEARNING_GOALS = 2
MAX_LEARNING_PREFERENCES = 3
MAX_PRIOR_SKILLS = 6
MAX_FORMAT_PREFERENCES = 3
MAX_QUICK_INSTRUCTIONS = 3

MIN_PATH_COURSES = 3
MAX_PATH_COURSES = 4
