import argparse
import asyncio
from datetime import datetime, timezone
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from decimal import Decimal

from sqlalchemy import delete, select

from app.constants import COURSE_CATEGORIES, DIFFICULTIES
from app.database import async_session_maker
from app.models import ActivityEvent, Course, VectorOutbox
from app.repositories.vector_outbox import create as create_outbox
from app.services.catalog_service import VECTOR_FIELDS, apply_course_record

SEED_COURSES = [
    {"title": "Introduction to Agentic AI", "slug": "introduction-to-agentic-ai", "category": "Agentic AI", "difficulty": "BEGINNER", "tags": ["agents", "foundations", "ai workflows"], "short_description": "Learn how goal-driven AI systems plan, call tools, and verify results.", "description": "Build a practical mental model for agent loops, tool boundaries, and reliable task completion. You will leave with small patterns for evaluating agent behavior without treating every prompt as magic.", "instructor": "Maya Iyer", "duration_minutes": 75, "price": Decimal("0.00")},
    {"title": "Advanced LangGraph Workflows", "slug": "advanced-langgraph-workflows", "category": "Agentic AI", "difficulty": "ADVANCED", "tags": ["langgraph", "state machines", "tool calling", "workflow reliability"], "short_description": "Design durable stateful workflows for tool-using AI applications.", "description": "Explore graph state, checkpoints, branching, and failure recovery through a production-shaped workflow. The course focuses on control flow and observability rather than generated recommendations.", "instructor": "Jon Bell", "duration_minutes": 240, "price": Decimal("79.00")},
    {"title": "Production RAG Systems", "slug": "production-rag-systems", "category": "Artificial Intelligence", "difficulty": "ADVANCED", "tags": ["rag", "retrieval", "evaluation", "grounding"], "short_description": "Move retrieval-augmented generation from prototype to dependable service.", "description": "Cover chunking decisions, retrieval evaluation, citation quality, and operational safeguards. Exercises turn a simple search-and-answer flow into a system that can be measured and improved.", "instructor": "Leena Das", "duration_minutes": 300, "price": Decimal("99.00")},
    {"title": "Multi-Agent Orchestration", "slug": "multi-agent-orchestration", "category": "Agentic AI", "difficulty": "ADVANCED", "tags": ["multi-agent", "orchestration", "delegation", "reliability"], "short_description": "Coordinate specialized agents with explicit contracts and bounded handoffs.", "description": "Learn when multiple agents add value, how to keep their responsibilities narrow, and how to test delegation paths. The examples emphasize predictable interfaces, budgets, and failure handling.", "instructor": "Owen Carter", "duration_minutes": 210, "price": Decimal("89.00")},
    {"title": "Python for Beginners", "slug": "python-for-beginners", "category": "Python", "difficulty": "BEGINNER", "tags": ["python", "programming", "fundamentals", "practice"], "short_description": "Start programming with clear Python examples and useful small projects.", "description": "Learn variables, functions, collections, files, and testing by building a set of approachable command-line tools. Each lesson adds one durable programming habit.", "instructor": "Ravi Shah", "duration_minutes": 180, "price": Decimal("0.00")},
    {"title": "FastAPI Backend Development", "slug": "fastapi-backend-development", "category": "Web Development", "difficulty": "INTERMEDIATE", "tags": ["fastapi", "apis", "python", "async"], "short_description": "Build typed, tested APIs with FastAPI and asynchronous Python.", "description": "Create a maintainable service with request validation, dependency injection, database sessions, and practical error handling. The final project is a small catalog API ready for deployment review.", "instructor": "Asha Menon", "duration_minutes": 220, "price": Decimal("59.00")},
    {"title": "Vector Databases in Practice", "slug": "vector-databases-in-practice", "category": "Artificial Intelligence", "difficulty": "INTERMEDIATE", "tags": ["vectors", "qdrant", "similarity search", "metadata filters"], "short_description": "Understand vector indexing, payloads, and reliable similarity search.", "description": "Work through collection design, point identifiers, metadata filtering, and synchronization concerns using realistic catalog data. You will also learn why vector state needs an operational source of truth.", "instructor": "Nikhil Rao", "duration_minutes": 165, "price": Decimal("69.00")},
    {"title": "Prompt Engineering Fundamentals", "slug": "prompt-engineering-fundamentals", "category": "Artificial Intelligence", "difficulty": "BEGINNER", "tags": ["prompting", "evaluation", "structured output"], "short_description": "Write clearer prompts and evaluate outputs with repeatable methods.", "description": "Learn task framing, examples, constraints, and structured outputs without relying on trial and error alone. Practical exercises show how to turn vague requests into testable behaviors.", "instructor": "Sara Kim", "duration_minutes": 100, "price": Decimal("29.00")},
    {"title": "AI Application Observability", "slug": "ai-application-observability", "category": "DevOps", "difficulty": "INTERMEDIATE", "tags": ["observability", "metrics", "tracing", "ai operations"], "short_description": "Instrument AI application behavior so reliability issues become diagnosable.", "description": "Define useful request metrics, capture safe operational context, and connect failures to user-visible outcomes. The course treats logs and traces as product infrastructure, not an afterthought.", "instructor": "Priya Nair", "duration_minutes": 150, "price": Decimal("65.00")},
    {"title": "Building Secure AI Products", "slug": "building-secure-ai-products", "category": "Cybersecurity", "difficulty": "ADVANCED", "tags": ["security", "threats", "ai products", "privacy"], "short_description": "Design AI product boundaries that protect users, data, and operations.", "description": "Map trust boundaries, constrain tool access, validate inputs, and plan incident responses for AI-enabled products. The material connects familiar application security practices to new model-driven risks.", "instructor": "Elena Torres", "duration_minutes": 240, "price": Decimal("85.00")},
    {"title": "Design Systems That Scale", "slug": "design-systems-that-scale", "category": "UI/UX Design", "difficulty": "INTERMEDIATE", "tags": ["design systems", "components", "tokens", "collaboration"], "short_description": "Create maintainable design systems that help teams ship consistently.", "description": "Explore component boundaries, tokens, documentation, and contribution workflows. You will practice making a system easier to use without turning every visual decision into bureaucracy.", "instructor": "Tara Joseph", "duration_minutes": 140, "price": Decimal("49.00")},
    {"title": "Reliable Data Pipelines", "slug": "reliable-data-pipelines", "category": "Data Science", "difficulty": "INTERMEDIATE", "tags": ["data pipelines", "quality", "scheduling", "etl"], "short_description": "Build data pipelines that are observable, repeatable, and safe to rerun.", "description": "Learn idempotent loads, data quality checks, backfills, and operational ownership through a small analytics pipeline. Every exercise addresses what happens when a step fails halfway through.", "instructor": "Mateo Silva", "duration_minutes": 195, "price": Decimal("64.00")},
    {"title": "Accessible Interface Craft", "slug": "accessible-interface-craft", "category": "UI/UX Design", "difficulty": "BEGINNER", "tags": ["accessibility", "semantic html", "keyboard", "inclusive design"], "short_description": "Build interfaces that remain understandable and usable for more people.", "description": "Practice semantic markup, keyboard navigation, focus states, forms, and readable content. The course uses small interface audits to make accessibility a normal delivery habit.", "instructor": "Nora Williams", "duration_minutes": 120, "price": Decimal("0.00")},
    {"title": "Applied Forecasting", "slug": "applied-forecasting", "category": "Machine Learning", "difficulty": "INTERMEDIATE", "tags": ["forecasting", "time series", "features", "evaluation"], "short_description": "Make useful forecasts while respecting time, seasonality, and uncertainty.", "description": "Build a forecasting workflow from baseline models through evaluation and communicating uncertainty. Examples show why a simple, well-tested forecast can outperform a complex model in practice.", "instructor": "Ishan Kapoor", "duration_minutes": 210, "price": Decimal("74.00")},
    {"title": "Practical Feature Engineering", "slug": "practical-feature-engineering", "category": "Machine Learning", "difficulty": "INTERMEDIATE", "tags": ["features", "machine learning", "data preparation", "leakage"], "short_description": "Turn messy source data into features that support honest model evaluation.", "description": "Work through temporal features, categorical data, missing values, and leakage checks. The emphasis is on repeatable transformations that survive the move from notebook to pipeline.", "instructor": "Kavya Singh", "duration_minutes": 175, "price": Decimal("62.00")},
    {"title": "Threat Modeling for Builders", "slug": "threat-modeling-for-builders", "category": "Cybersecurity", "difficulty": "BEGINNER", "tags": ["threat modeling", "security design", "risk", "web"], "short_description": "Find and prioritize security risks before they become expensive incidents.", "description": "Use simple threat-modeling diagrams, abuse cases, and risk scoring to review a real application. You will learn a lightweight practice that fits into normal product planning.", "instructor": "Diego Morales", "duration_minutes": 90, "price": Decimal("25.00")},
    {"title": "Product Discovery Fieldwork", "slug": "product-discovery-fieldwork", "category": "Product Management", "difficulty": "BEGINNER", "tags": ["discovery", "user research", "product strategy"], "short_description": "Turn customer conversations into clearer product decisions.", "description": "Plan interviews, separate observations from assumptions, and synthesize evidence into product opportunities. The exercises focus on learning quickly without pretending every request is a roadmap commitment.", "instructor": "Meera Patel", "duration_minutes": 110, "price": Decimal("35.00")},
    {"title": "Secure Authentication Foundations", "slug": "secure-authentication-foundations", "category": "Cybersecurity", "difficulty": "INTERMEDIATE", "tags": ["authentication", "sessions", "csrf", "passwords"], "short_description": "Implement authentication flows with safer password and session practices.", "description": "Review password hashing, session cookies, CSRF defenses, authorization checks, and account lifecycle concerns. The examples are framework-neutral but concrete enough to apply immediately.", "instructor": "Fatima Ahmed", "duration_minutes": 160, "price": Decimal("55.00")},
    {"title": "Modern SQL for Analysts", "slug": "modern-sql-for-analysts", "category": "Data Science", "difficulty": "BEGINNER", "tags": ["sql", "analytics", "joins", "aggregates"], "short_description": "Answer business questions with readable, reliable SQL.", "description": "Practice joins, grouping, window functions, and careful filtering against realistic datasets. Each query is shaped around a decision an analyst may need to explain to a teammate.", "instructor": "Arjun Mehta", "duration_minutes": 130, "price": Decimal("39.00")},
    {"title": "Kubernetes Delivery Basics", "slug": "kubernetes-delivery-basics", "category": "DevOps", "difficulty": "INTERMEDIATE", "tags": ["kubernetes", "containers", "deployments", "operations"], "short_description": "Understand the Kubernetes objects that make application delivery repeatable.", "description": "Deploy a small service, configure health checks, manage secrets safely, and inspect rollout behavior. The course explains the operational concepts behind the YAML rather than asking learners to memorize it.", "instructor": "Hugo Martin", "duration_minutes": 190, "price": Decimal("68.00")},
    {"title": "Experiment Design Essentials", "slug": "experiment-design-essentials", "category": "Data Science", "difficulty": "INTERMEDIATE", "tags": ["experiments", "metrics", "causal thinking", "analysis"], "short_description": "Plan product experiments that produce interpretable evidence.", "description": "Define hypotheses, guardrail metrics, samples, and analysis plans before looking at results. You will practice spotting common decision errors in experiments that look convincing at first glance.", "instructor": "Laila Roy", "duration_minutes": 145, "price": Decimal("47.00")},
    {"title": "Cloud Architecture Patterns", "slug": "cloud-architecture-patterns", "category": "Cloud Computing", "difficulty": "ADVANCED", "tags": ["cloud", "architecture", "scalability", "reliability"], "short_description": "Choose cloud architecture patterns with explicit trade-offs.", "description": "Compare queues, caches, databases, and service boundaries through workload-shaped scenarios. The goal is not a universal diagram; it is a better way to reason about reliability, cost, and change.", "instructor": "Victor Chen", "duration_minutes": 225, "price": Decimal("82.00")},
    {"title": "TypeScript for Backend Teams", "slug": "typescript-for-backend-teams", "category": "Web Development", "difficulty": "INTERMEDIATE", "tags": ["typescript", "node", "types", "apis"], "short_description": "Use TypeScript to make backend services clearer and safer to change.", "description": "Learn type modelling, runtime validation, async workflows, and service boundaries through backend examples. The course connects language features to maintenance problems teams actually face.", "instructor": "Rachel Green", "duration_minutes": 170, "price": Decimal("52.00")},
    {"title": "Python Automation Studio", "slug": "python-automation-studio", "category": "Python", "difficulty": "INTERMEDIATE", "tags": ["python", "automation", "cli", "files"], "short_description": "Automate repetitive work with small, dependable Python tools.", "description": "Build scripts for files, APIs, reports, and scheduled jobs while learning practical error handling and logging. The project is intentionally modest: useful automation that someone else can trust.", "instructor": "Sanjay Rao", "duration_minutes": 155, "price": Decimal("44.00")},
    {"title": "Metrics That Drive Decisions", "slug": "metrics-that-drive-decisions", "category": "Business Analytics", "difficulty": "BEGINNER", "tags": ["metrics", "dashboards", "business", "decision making"], "short_description": "Choose metrics that clarify decisions instead of filling dashboards.", "description": "Connect business questions to definitions, dimensions, and review rhythms. Exercises expose vanity metrics and show how a small set of well-owned measures can guide action.", "instructor": "Grace Liu", "duration_minutes": 105, "price": Decimal("32.00")},
    {"title": "Shipping with Event-Driven APIs", "slug": "shipping-with-event-driven-apis", "category": "Web Development", "difficulty": "ADVANCED", "tags": ["events", "apis", "messaging", "idempotency"], "short_description": "Design event-driven APIs that tolerate retries and partial failure.", "description": "Build an event flow with durable delivery, stable identities, and safe consumers. You will learn when an outbox helps and where transactional boundaries should remain explicit.", "instructor": "Noah Brooks", "duration_minutes": 205, "price": Decimal("72.00")},
    {"title": "Visual Storytelling with Data", "slug": "visual-storytelling-with-data", "category": "Data Science", "difficulty": "BEGINNER", "tags": ["data visualization", "storytelling", "charts", "communication"], "short_description": "Make charts that help people understand what the data says.", "description": "Choose visual encodings, remove distracting decoration, and write a clear narrative around evidence. The course uses before-and-after critiques to build a stronger visual editing instinct.", "instructor": "Bea Okafor", "duration_minutes": 115, "price": Decimal("28.00")},
    {"title": "Evaluation-First Machine Learning", "slug": "evaluation-first-machine-learning", "category": "Machine Learning", "difficulty": "ADVANCED", "tags": ["machine learning", "evaluation", "benchmarks", "error analysis"], "short_description": "Improve machine-learning systems by measuring the right failures first.", "description": "Design representative test sets, slice errors, and compare changes with discipline. The material helps teams avoid shipping impressive averages that hide unacceptable behavior.", "instructor": "Yuki Tan", "duration_minutes": 230, "price": Decimal("91.00")},
    {"title": "DevOps Incident Readiness", "slug": "devops-incident-readiness", "category": "DevOps", "difficulty": "INTERMEDIATE", "tags": ["incidents", "runbooks", "on-call", "reliability"], "short_description": "Prepare teams to detect, contain, and learn from service incidents.", "description": "Create practical runbooks, define escalation paths, and run blameless incident reviews. Scenarios focus on reducing confusion during pressure and converting lessons into safer systems.", "instructor": "Thomas Reed", "duration_minutes": 135, "price": Decimal("46.00")},
    {"title": "Responsible AI Product Strategy", "slug": "responsible-ai-product-strategy", "category": "Product Management", "difficulty": "INTERMEDIATE", "tags": ["responsible ai", "product strategy", "risk", "governance"], "short_description": "Make responsible AI trade-offs part of ordinary product strategy.", "description": "Map affected people, define acceptable use, and plan evaluation and escalation before launch. The course gives product teams a practical language for risk without pretending governance is a single checklist.", "instructor": "Amara Williams", "duration_minutes": 150, "price": Decimal("58.00")},
    {"title": "Autonomous Agent Evaluation & Red Teaming", "slug": "autonomous-agent-evaluation-and-red-teaming", "category": "Agentic AI", "difficulty": "ADVANCED", "tags": ["agent evaluation", "red teaming", "safety", "benchmarks"], "short_description": "Audit autonomous agent resilience through adversarial test suits and behavioral red teaming.", "description": "Build rigorous evaluation loops to stress-test autonomous agents. You will design adversarial test scenarios, measure tool abuse risks, and benchmark decision safety before deployment.", "instructor": "Dr. Evelyn Vance", "duration_minutes": 210, "price": Decimal("89.00")},
    {"title": "Memory Architectures for Long-Context Agents", "slug": "memory-architectures-for-long-context-agents", "category": "Agentic AI", "difficulty": "INTERMEDIATE", "tags": ["agent memory", "vector stores", "episodes", "context retention"], "short_description": "Implement episodic, semantic, and working memory buffers for persistent AI agents.", "description": "Explore stateful memory architectures that allow AI agents to maintain coherent long-term user context without overflowing token budgets or leaking cross-session state.", "instructor": "Marcus Vance", "duration_minutes": 180, "price": Decimal("69.00")},
    {"title": "Tool Execution & API Synthesizers", "slug": "tool-execution-and-api-synthesizers", "category": "Agentic AI", "difficulty": "INTERMEDIATE", "tags": ["tool calling", "api synthesis", "json schema", "sandboxing"], "short_description": "Synthesize dynamic API calls and isolate tool execution environments for autonomous agents.", "description": "Construct safe tool execution gateways, auto-generate JSON schemas from OpenAPI specs, and implement strict sandboxing to isolate untrusted agent runtime tools.", "instructor": "Siddharth Verma", "duration_minutes": 160, "price": Decimal("59.00")},
    {"title": "Fine-Tuning Open Source LLMs", "slug": "fine-tuning-open-source-llms", "category": "Artificial Intelligence", "difficulty": "ADVANCED", "tags": ["lora", "qlora", "huggingface", "model alignment"], "short_description": "Master parameter-efficient fine-tuning (PEFT) and LoRA techniques on open-weights models.", "description": "Prepare instruction datasets, optimize memory efficiency with QLoRA, and fine-tune open language models like Llama and Mistral for specific enterprise domain tasks.", "instructor": "Dr. Aris Thorne", "duration_minutes": 270, "price": Decimal("99.00")},
    {"title": "Multimodal AI System Engineering", "slug": "multimodal-ai-system-engineering", "category": "Artificial Intelligence", "difficulty": "ADVANCED", "tags": ["multimodal", "vision llms", "embeddings", "audio processing"], "short_description": "Build end-to-end applications combining vision, speech, and textual understanding.", "description": "Process cross-modal embeddings, integrate Vision-Language models into RAG pipelines, and build real-time multi-modal streaming workflows.", "instructor": "Elena Rostova", "duration_minutes": 240, "price": Decimal("85.00")},
    {"title": "Small Language Models in Edge Production", "slug": "small-language-models-in-edge-production", "category": "Artificial Intelligence", "difficulty": "INTERMEDIATE", "tags": ["slm", "quantization", "edge computing", "onnx"], "short_description": "Deploy low-latency, quantized small language models directly on edge devices and local hardware.", "description": "Learn model quantization techniques (GGUF, AWQ, ONNX), evaluate local inference runtimes, and deploy high-speed private AI endpoints.", "instructor": "Kenji Sato", "duration_minutes": 195, "price": Decimal("65.00")},
    {"title": "MLOps Model Monitoring & Drift Detection", "slug": "mlops-model-monitoring-and-drift-detection", "category": "Machine Learning", "difficulty": "INTERMEDIATE", "tags": ["mlops", "data drift", "model monitoring", "evidently"], "short_description": "Detect statistical feature drift and performance decay in production ML models.", "description": "Build continuous monitoring pipelines that alert on feature distribution shifts, concept drift, and prediction latency anomalies in deployed prediction models.", "instructor": "Hannah Lindqvist", "duration_minutes": 200, "price": Decimal("75.00")},
    {"title": "Graph Neural Networks in Practice", "slug": "graph-neural-networks-in-practice", "category": "Machine Learning", "difficulty": "ADVANCED", "tags": ["gnn", "pytorch geometric", "network analysis", "deep learning"], "short_description": "Model complex relational graph data using PyTorch Geometric and GNN architectures.", "description": "Understand node embeddings, graph convolutions, link prediction, and sub-graph classification for fraud detection, recommendation engines, and biological networks.", "instructor": "Prof. Julian Kross", "duration_minutes": 250, "price": Decimal("89.00")},
    {"title": "Explainable AI & Interpretable Models", "slug": "explainable-ai-and-interpretable-models", "category": "Machine Learning", "difficulty": "INTERMEDIATE", "tags": ["xai", "shap", "lime", "model interpretability"], "short_description": "Uncover model predictions using SHAP values, LIME feature attribution, and partial dependence plots.", "description": "Deconstruct opaque black-box models into auditable, interpretable feature attributions for regulated industries like finance, healthcare, and risk assessment.", "instructor": "Deepak Sen", "duration_minutes": 150, "price": Decimal("55.00")},
    {"title": "Real-Time Streaming Analytics with Apache Flink", "slug": "real-time-streaming-analytics-with-apache-flink", "category": "Data Science", "difficulty": "ADVANCED", "tags": ["streaming", "flink", "real-time", "event streams"], "short_description": "Process stateful real-time data streams with low latency using Apache Flink and Kafka.", "description": "Master event-time temporal joins, sliding window aggregations, state checkpointing, and exactly-once processing guarantees in distributed streaming pipelines.", "instructor": "Viktor Hansen", "duration_minutes": 260, "price": Decimal("95.00")},
    {"title": "Polars for High-Performance Data Processing", "slug": "polars-for-high-performance-data-processing", "category": "Data Science", "difficulty": "INTERMEDIATE", "tags": ["polars", "python", "dataframe", "performance"], "short_description": "Accelerate Python data transformations using the lightning-fast Polars Rust engine.", "description": "Replace sluggish Pandas code with lazy evaluation queries, multi-threaded execution, and memory-efficient streaming operations for gigabyte-scale datasets.", "instructor": "Sofia Rossi", "duration_minutes": 135, "price": Decimal("45.00")},
    {"title": "Causal Inference for Data Science", "slug": "causal-inference-for-data-science", "category": "Data Science", "difficulty": "ADVANCED", "tags": ["causal inference", "econometrics", "dowhy", "counterfactuals"], "short_description": "Move beyond correlation to measure true causal impact in observational business data.", "description": "Implement propensity score matching, instrumental variables, and causal graphs using Python DoWhy to evaluate product interventions without A/B testing.", "instructor": "Dr. Lars Mikkelsen", "duration_minutes": 220, "price": Decimal("79.00")},
    {"title": "Python Concurrency: Asyncio & Multiprocessing", "slug": "python-concurrency-asyncio-and-multiprocessing", "category": "Python", "difficulty": "ADVANCED", "tags": ["concurrency", "asyncio", "multiprocessing", "threading"], "short_description": "Write high-throughput Python applications using event loops, thread pools, and process pools.", "description": "Understand GIL constraints, master `asyncio` task management, prevent race conditions, and leverage multi-core CPU scaling for parallel workloads.", "instructor": "Gwen Tennyson", "duration_minutes": 210, "price": Decimal("69.00")},
    {"title": "Design Patterns in Modern Python", "slug": "design-patterns-in-modern-python", "category": "Python", "difficulty": "INTERMEDIATE", "tags": ["design patterns", "clean code", "object-oriented", "pythonic"], "short_description": "Apply modern Creational, Structural, and Behavioral patterns tailored for idiomatic Python 3.", "description": "Learn dataclasses, protocols, dependency injection, factory methods, and strategy patterns to write maintainable Python codebases that scale cleanly.", "instructor": "Nigel Thorne", "duration_minutes": 175, "price": Decimal("55.00")},
    {"title": "Next.js Fullstack Architecture", "slug": "nextjs-fullstack-architecture", "category": "Web Development", "difficulty": "INTERMEDIATE", "tags": ["nextjs", "react", "server components", "fullstack"], "short_description": "Build high-performance web applications with React Server Components and Next.js App Router.", "description": "Master server actions, streaming SSR, dynamic caching revalidation, and API route handlers for modern, SEO-friendly fullstack applications.", "instructor": "Chloe Bennett", "duration_minutes": 240, "price": Decimal("79.00")},
    {"title": "Web Performance Optimization Masterclass", "slug": "web-performance-optimization-masterclass", "category": "Web Development", "difficulty": "ADVANCED", "tags": ["core web vitals", "performance", "rendering", "caching"], "short_description": "Optimize Core Web Vitals (LCP, INP, CLS) and minimize bundle sizes for sub-second page loads.", "description": "Analyze performance traces, eliminate layout shifts, optimize critical rendering paths, and configure CDN caching strategies for production web apps.", "instructor": "Liam O'Connor", "duration_minutes": 180, "price": Decimal("59.00")},
    {"title": "Building Real-Time Web Apps with WebSockets", "slug": "building-real-time-web-apps-with-websockets", "category": "Web Development", "difficulty": "INTERMEDIATE", "tags": ["websockets", "real-time", "sse", "event-driven"], "short_description": "Create bi-directional, low-latency live features using WebSockets and Server-Sent Events.", "description": "Architect scalable real-time notification feeds, live collaborative dashboards, and WebSocket reconnection strategies with Python and JavaScript.", "instructor": "Ananya Deshmukh", "duration_minutes": 160, "price": Decimal("49.00")},
    {"title": "Terraform Infrastructure as Code", "slug": "terraform-infrastructure-as-code", "category": "Cloud Computing", "difficulty": "INTERMEDIATE", "tags": ["terraform", "iac", "cloud infrastructure", "automation"], "short_description": "Provision and manage reproducible multi-cloud infrastructure with HashiCorp Terraform.", "description": "Write modular HCL code, manage remote state backends with locking, configure modules, and run safe speculative plan previews in automated CI/CD pipelines.", "instructor": "Soren Madsen", "duration_minutes": 190, "price": Decimal("65.00")},
    {"title": "Serverless Architectures on AWS", "slug": "serverless-architectures-on-aws", "category": "Cloud Computing", "difficulty": "ADVANCED", "tags": ["serverless", "aws lambda", "eventbridge", "cloud native"], "short_description": "Design event-driven serverless backends using AWS Lambda, API Gateway, and EventBridge.", "description": "Eliminate server management overhead by constructing asynchronous, auto-scaling microservices with robust cold-start optimization and error dead-letter queues.", "instructor": "Brenda Vance", "duration_minutes": 210, "price": Decimal("75.00")},
    {"title": "Cloud Security Posture Management", "slug": "cloud-security-posture-management", "category": "Cybersecurity", "difficulty": "ADVANCED", "tags": ["cloud security", "cspm", "iam", "compliance"], "short_description": "Enforce continuous compliance, IAM policies, and cloud misconfiguration detection across environments.", "description": "Implement automated policy-as-code checks, remediate dangerous public storage buckets, and manage least-privilege identity access management (IAM) across cloud fleets.", "instructor": "Dimitri Volkov", "duration_minutes": 200, "price": Decimal("79.00")},
    {"title": "Zero Trust Network Architecture", "slug": "zero-trust-network-architecture", "category": "Cybersecurity", "difficulty": "INTERMEDIATE", "tags": ["zero trust", "network security", "identity", "microsegmentation"], "short_description": "Implement 'never trust, always verify' security perimeters with microsegmentation and identity-aware proxies.", "description": "Design identity-centric access control, dynamic device health verification, and encrypted network tunnels to secure remote workforces against lateral intrusion.", "instructor": "Sarah Jenkins", "duration_minutes": 165, "price": Decimal("59.00")},
    {"title": "AI Product Roadmap Strategy", "slug": "ai-product-roadmap-strategy", "category": "Product Management", "difficulty": "INTERMEDIATE", "tags": ["product strategy", "ai roadmaps", "prioritization", "value prop"], "short_description": "Define clear AI product value propositions, ROI metrics, and feasibility milestones.", "description": "Evaluate feasibility versus impact for AI features, construct product roadmaps that accommodate model uncertainty, and align engineering capabilities with business goals.", "instructor": "Karan Malhotra", "duration_minutes": 140, "price": Decimal("49.00")},
    {"title": "Growth Product Management Essentials", "slug": "growth-product-management-essentials", "category": "Product Management", "difficulty": "BEGINNER", "tags": ["growth", "funnel optimization", "retention", "monetization"], "short_description": "Drive user acquisition, onboarding conversion, and long-term product retention.", "description": "Map user growth funnels, design friction-free onboarding flows, run rapid growth experiments, and build sustainable monetization loops.", "instructor": "Emma Watson", "duration_minutes": 120, "price": Decimal("39.00")},
    {"title": "Advanced Motion Design for Web Interfaces", "slug": "advanced-motion-design-for-web-interfaces", "category": "UI/UX Design", "difficulty": "ADVANCED", "tags": ["motion design", "framer motion", "micro-interactions", "ui animation"], "short_description": "Craft purposeful, fluid UI animations and micro-interactions that elevate user delight.", "description": "Learn animation timing curves, physics-based springs, gesture-driven transitions, and accessible reduced-motion fallbacks for modern web UIs.", "instructor": "Leo Martinez", "duration_minutes": 160, "price": Decimal("55.00")},
    {"title": "Design Systems for Enterprise Apps", "slug": "design-systems-for-enterprise-apps", "category": "UI/UX Design", "difficulty": "INTERMEDIATE", "tags": ["enterprise ui", "design tokens", "component libraries", "figma"], "short_description": "Architect scalable UI component libraries and design tokens for complex enterprise workflows.", "description": "Design accessible data tables, multi-step forms, and dense dashboard layouts in Figma and CSS while maintaining strict visual cohesion across engineering teams.", "instructor": "Teresa Zhang", "duration_minutes": 180, "price": Decimal("65.00")},
    {"title": "Executive Financial Modeling & Analysis", "slug": "executive-financial-modeling-and-analysis", "category": "Business Analytics", "difficulty": "INTERMEDIATE", "tags": ["financial modeling", "excel", "unit economics", "forecasting"], "short_description": "Build three-statement financial models, forecast cash flows, and analyze unit economics.", "description": "Master revenue forecasting, CAC/LTV sensitivity analysis, scenario planning, and executive presentation of key financial health metrics.", "instructor": "Richard Sterling", "duration_minutes": 190, "price": Decimal("69.00")},
    {"title": "Cohort Analysis & Customer Lifetime Value", "slug": "cohort-analysis-and-customer-lifetime-value", "category": "Business Analytics", "difficulty": "INTERMEDIATE", "tags": ["cohorts", "ltv", "churn prediction", "customer analytics"], "short_description": "Measure customer retention curves, predict churn risk, and calculate true LTV.", "description": "Analyze user cohort retention tables, model customer acquisition cost payback periods, and build actionable customer segmentation strategies.", "instructor": "Alisha Fernandez", "duration_minutes": 150, "price": Decimal("49.00")},
    {"title": "GitOps Pipelines with ArgoCD & Flux", "slug": "gitops-pipelines-with-argocd-and-flux", "category": "DevOps", "difficulty": "ADVANCED", "tags": ["gitops", "argocd", "kubernetes", "continuous delivery"], "short_description": "Implement declarative continuous deployment pipelines for Kubernetes using Git as the source of truth.", "description": "Set up automated cluster reconciliation with ArgoCD, handle multi-environment Kustomize overlays, and enable zero-downtime progressive rollouts.", "instructor": "Eirik Solberg", "duration_minutes": 220, "price": Decimal("79.00")},
    {"title": "Site Reliability Engineering Practices", "slug": "site-reliability-engineering-practices", "category": "DevOps", "difficulty": "INTERMEDIATE", "tags": ["sre", "slos", "error budgets", "reliability"], "short_description": "Define Service Level Objectives (SLOs), manage error budgets, and reduce operational toil.", "description": "Translate business expectations into measurable SLIs, set up error budget burn rate alerts, and implement automated toil reduction practices.", "instructor": "Naomi Takahashi", "duration_minutes": 180, "price": Decimal("65.00")},
    {"title": "Cloud Cost Optimization & FinOps", "slug": "cloud-cost-optimization-and-finops", "category": "Cloud Computing", "difficulty": "INTERMEDIATE", "tags": ["finops", "cloud cost", "aws", "optimization"], "short_description": "Audit cloud resource utilization, track cost allocation tags, and implement automated scaling policies.", "description": "Learn FinOps best practices to analyze cloud spending, set up budget alerts, right-size instances, and eliminate waste across multi-cloud environments.", "instructor": "Marcus Thorne", "duration_minutes": 150, "price": Decimal("49.00")},
]



from app.data.course_details import get_course_detail

SEED_FIELDS = VECTOR_FIELDS + ("is_featured", "thumbnail_url", "what_you_will_learn", "prerequisites", "target_audience", "tools_used", "estimated_effort", "curriculum", "final_project", "instructor_bio", "faqs")


def _record(definition: dict) -> dict:
    slug = definition["slug"]
    thumbnail_url = f"/static/images/courses/{slug}.png" if slug == "introduction-to-agentic-ai" else f"/static/images/courses/{slug}.svg"
    details = get_course_detail(
        definition["slug"],
        definition["title"],
        definition["category"],
        definition["instructor"],
        definition["description"],
        definition["short_description"],
        definition["tags"],
        definition["duration_minutes"]
    )
    return {
        **definition,
        **details,
        "thumbnail_url": thumbnail_url,
        "currency": "USD",
        "is_featured": definition["slug"] in {"introduction-to-agentic-ai", "production-rag-systems", "python-for-beginners"},
        "is_active": True
    }


SEED_COURSES = [_record(item) for item in SEED_COURSES]


def validate_seed_courses() -> None:
    seen = set()
    for course in SEED_COURSES:
        if course["slug"] in seen or course["category"] not in COURSE_CATEGORIES or course["difficulty"] not in DIFFICULTIES:
            raise ValueError(f"Invalid seed course: {course['slug']}")
        if not 3 <= len(course["tags"]) <= 5 or any(tag != tag.strip().lower() for tag in course["tags"]):
            raise ValueError(f"Invalid seed tags: {course['slug']}")
        seen.add(course["slug"])


validate_seed_courses()


def _changed(course: Course, record: dict) -> bool:
    return any(getattr(course, field) != record[field] for field in SEED_FIELDS)


def _apply(course: Course, record: dict) -> bool:
    return apply_course_record(course, record)


async def main(*, reset: bool = False, sync_existing: bool = False, dry_run: bool = False) -> dict:
    validate_seed_courses()
    sync_existing = sync_existing or dry_run
    report = {"inserted": 0, "changed": 0, "unchanged": 0, "outbox": 0}
    async with async_session_maker() as db:
        if reset:
            await db.execute(delete(ActivityEvent))
            await db.execute(delete(VectorOutbox))
            await db.execute(delete(Course))
        existing = {row.slug: row for row in (await db.scalars(select(Course))).all()}
        for record in SEED_COURSES:
            course = existing.get(record["slug"])
            if course:
                if not sync_existing:
                    report["unchanged"] += 1
                    continue
                if not _changed(course, record):
                    report["unchanged"] += 1
                    continue
                vector_changed = _apply(course, record)
                report["changed"] += 1
                if vector_changed:
                    db.add(create_outbox(course, "UPSERT" if course.is_active else "DELETE", datetime.now(timezone.utc).replace(tzinfo=None)))
                    report["outbox"] += 1
                continue
            course_data = {**record, "tags": list(record["tags"]), "version": 1, "vector_status": "PENDING"}
            course = Course(**course_data)
            db.add(course)
            await db.flush()
            db.add(create_outbox(course, "UPSERT", datetime.now(timezone.utc).replace(tzinfo=None)))
            report["inserted"] += 1
            report["outbox"] += 1
        if dry_run:
            await db.rollback()
        else:
            await db.commit()
    print("Seed report:", ", ".join(f"{key}={value}" for key, value in report.items()))
    return report


def cli() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--sync-existing", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--reset", action="store_true")
    parser.add_argument("--confirm-reset", action="store_true")
    args = parser.parse_args()
    if args.reset and not args.confirm_reset:
        parser.error("--reset is development-only and requires --confirm-reset")
    asyncio.run(main(reset=args.reset, sync_existing=args.sync_existing, dry_run=args.dry_run))


if __name__ == "__main__":
    cli()
